<a href="https://colab.research.google.com/github/MANDEEP9711/panda_practices-/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# New Section

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("arianazmoudeh/airbnbopendata")

print("Path to dataset files:", path)

/usr/local/python/3.12.1/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Downloading to /home/codespace/.cache/kagglehub/datasets/arianazmoudeh/airbnbopendata/1.archive...

100%|██████████| 10.5M/10.5M [00:02<00:00, 4.83MB/s]

Extracting files...

Path to dataset files: /home/codespace/.cache/kagglehub/datasets/arianazmoudeh/airbnbopendata/versions/1

In [3]:
import numpy as np
import pandas as pd
import os

print(os.listdir(path))
fil=os.path.join(path,"Airbnb_Open_Data.csv")
print(fil)

['Airbnb_Open_Data.csv']
/home/codespace/.cache/kagglehub/datasets/arianazmoudeh/airbnbopendata/versions/1/Airbnb_Open_Data.csv

In [6]:
data_set=pd.read_csv(fil)
print(data_set.head(5))

        id                                              NAME      host id  \
0  1001254                Clean & quiet apt home by the park  80014485718
1  1002102                             Skylit Midtown Castle  52335172823
2  1002403               THE VILLAGE OF HARLEM....NEW YORK !  78829239556
3  1002755                                               NaN  85098326012
4  1003689  Entire Apt: Spacious Studio/Loft by central park  92037596077

  host_identity_verified host name neighbourhood group neighbourhood  \
0            unconfirmed  Madaline            Brooklyn    Kensington
1               verified     Jenna           Manhattan       Midtown
2                    NaN     Elise           Manhattan        Harlem
3            unconfirmed     Garry            Brooklyn  Clinton Hill
4               verified    Lyndon           Manhattan   East Harlem

        lat      long        country  ... service fee minimum nights  \
0  40.64749 -73.97237  United States  ...       $193            10.0
1  40.75362 -73.98377  United States  ...        $28            30.0
2  40.80902 -73.94190  United States  ...       $124             3.0
3  40.68514 -73.95976  United States  ...        $74            30.0
4  40.79851 -73.94399  United States  ...        $41            10.0

  number of reviews last review  reviews per month review rate number  \
0               9.0  10/19/2021               0.21                4.0
1              45.0   5/21/2022               0.38                4.0
2               0.0         NaN                NaN                5.0
3             270.0    7/5/2019               4.64                4.0
4               9.0  11/19/2018               0.10                3.0

  calculated host listings count  availability 365  \
0                            6.0             286.0
1                            2.0             228.0
2                            1.0             352.0
3                            1.0             322.0
4                            1.0             289.0

                                         house_rules license
0  Clean up and treat the home the way you'd like...     NaN
1  Pet friendly but please confirm with me if the...     NaN
2  I encourage you to use my kitchen, cooking and...     NaN
3                                                NaN     NaN
4  Please no smoking in the house, porch or on th...     NaN

[5 rows x 26 columns]

/tmp/ipykernel_7197/2154457382.py:1: DtypeWarning: Columns (0: license) have mixed types. Specify dtype option on import or set low_memory=False.
  data_set=pd.read_csv(fil)

In [7]:
data_set=data_set.drop(["last review","reviews per month","license","lat","long"],axis=1)
null_data=data_set.isnull().sum()

In [8]:
null_data=data_set.isnull().sum()
data_set["house_rules"].fillna("no rules",inplace=True)
print(null_data)

id                                    0
NAME                                250
host id                               0
host_identity_verified              289
host name                           406
neighbourhood group                  29
neighbourhood                        16
country                             532
country code                        131
instant_bookable                    105
cancellation_policy                  76
room type                             0
Construction year                   214
price                               247
service fee                         273
minimum nights                      409
number of reviews                   183
review rate number                  326
calculated host listings count      319
availability 365                    448
house_rules                       52131
dtype: int64

/tmp/ipykernel_7197/3165785002.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  data_set["house_rules"].fillna("no rules",inplace=True)

In [9]:
data_set.dropna(axis=0,inplace=True)
print(data_set)

             id                                              NAME  \
0       1001254                Clean & quiet apt home by the park
1       1002102                             Skylit Midtown Castle
4       1003689  Entire Apt: Spacious Studio/Loft by central park
5       1004098         Large Cozy 1 BR Apartment In Midtown East
7       1005202                                   BlissArtsSpace!
...         ...                                               ...
102591  6090781                Columbus Ave Apt 1 block from Park
102592  6091333               3BR/1 Ba in TriBeCa w/ outdoor deck
102593  6091885               Welcoming, Clean, Cheap on St Marks
102594  6092437                        Spare room in Williamsburg
102595  6092990                     Best Location near Columbia U

            host id host_identity_verified host name neighbourhood group  \
0       80014485718            unconfirmed  Madaline            Brooklyn
1       52335172823               verified     Jenna           Manhattan
4       92037596077               verified    Lyndon           Manhattan
5       45498551794               verified  Michelle           Manhattan
7       90821839709            unconfirmed      Emma            Brooklyn
...             ...                    ...       ...                 ...
102591  50908010324               verified  Lawrence           Manhattan
102592  53266862889            unconfirmed      Nick           Manhattan
102593  33188605074               verified    Felipe           Manhattan
102594  12312296767               verified      Krik            Brooklyn
102595  77864383453            unconfirmed     Mifan           Manhattan

              neighbourhood        country country code instant_bookable  ...  \
0                Kensington  United States           US            False  ...
1                   Midtown  United States           US            False  ...
4               East Harlem  United States           US            False  ...
5               Murray Hill  United States           US             True  ...
7        Bedford-Stuyvesant  United States           US            False  ...
...                     ...            ...          ...              ...  ...
102591      Upper West Side  United States           US            False  ...
102592              Tribeca  United States           US            False  ...
102593         East Village  United States           US             True  ...
102594         Williamsburg  United States           US            False  ...
102595  Morningside Heights  United States           US             True  ...

              room type Construction year    price service fee minimum nights  \
0          Private room            2020.0    $966        $193            10.0
1       Entire home/apt            2007.0    $142         $28            30.0
4       Entire home/apt            2009.0    $204         $41            10.0
5       Entire home/apt            2013.0    $577        $115             3.0
7          Private room            2009.0  $1,060        $212            45.0
...                 ...               ...      ...         ...            ...
102591  Entire home/apt            2005.0  $1,139        $228             5.0
102592  Entire home/apt            2016.0    $787        $157             1.0
102593     Private room            2017.0  $1,099        $220             1.0
102594     Private room            2003.0    $844        $169             1.0
102595     Private room            2016.0    $837        $167             1.0

        number of reviews  review rate number  calculated host listings count  \
0                     9.0                 4.0                             6.0
1                    45.0                 4.0                             2.0
4                     9.0                 3.0                             1.0
5                    74.0                 3.0                             1.0
7                    49.0                 5.0                             1.0
...                   ...                 ...                             ...
102591               17.0                 5.0                             1.0
102592                0.0                 2.0                             1.0
102593                8.0                 4.0                             2.0
102594                0.0                 3.0                             1.0
102595                1.0                 2.0                             2.0

        availability 365                                        house_rules
0                  286.0  Clean up and treat the home the way you'd like...
1                  228.0  Pet friendly but please confirm with me if the...
4                  289.0  Please no smoking in the house, porch or on th...
5                  374.0                  No smoking, please, and no drugs.
7                  219.0  House Guidelines for our BnB We are delighted ...
...                  ...                                                ...
102591             134.0                                             #NAME?
102592             177.0  Guests should treat my home as if it were thei...
102593             152.0  * No smoking indoors.  * No pets  * No loud/la...
102594             227.0  No Smoking No Parties or Events of any kind Pl...
102595             395.0  House rules: Guests agree to the following ter...

[48699 rows x 21 columns]

In [10]:
data_set.info()

<class 'pandas.DataFrame'>
Index: 48699 entries, 0 to 102595
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48699 non-null  int64
 1   NAME                            48699 non-null  str
 2   host id                         48699 non-null  int64
 3   host_identity_verified          48699 non-null  str
 4   host name                       48699 non-null  str
 5   neighbourhood group             48699 non-null  str
 6   neighbourhood                   48699 non-null  str
 7   country                         48699 non-null  str
 8   country code                    48699 non-null  str
 9   instant_bookable                48699 non-null  object
 10  cancellation_policy             48699 non-null  str
 11  room type                       48699 non-null  str
 12  Construction year               48699 non-null  float64
 13  price                           48699 non-null  str
 14  service fee                     48699 non-null  str
 15  minimum nights                  48699 non-null  float64
 16  number of reviews               48699 non-null  float64
 17  review rate number              48699 non-null  float64
 18  calculated host listings count  48699 non-null  float64
 19  availability 365                48699 non-null  float64
 20  house_rules                     48699 non-null  str
dtypes: float64(6), int64(2), object(1), str(12)
memory usage: 8.2+ MB

In [11]:
data_set.drop_duplicates(inplace=True)
data_set.duplicated().sum()

np.int64(0)

In [12]:
data_set.rename(columns={"level_0":"index"},inplace=True)
print(data_set.head(20))

          id                                               NAME      host id  \
0    1001254                 Clean & quiet apt home by the park  80014485718
1    1002102                              Skylit Midtown Castle  52335172823
4    1003689   Entire Apt: Spacious Studio/Loft by central park  92037596077
5    1004098          Large Cozy 1 BR Apartment In Midtown East  45498551794
7    1005202                                    BlissArtsSpace!  90821839709
8    1005754                    Large Furnished Room Near B'way  79384379533
9    1006307                 Cozy Clean Guest Room - Family Apt  75527839483
11   1007411                   Beautiful 1br on Upper West Side  18824631834
38   1022323                          Cute apt in artist's home  88653822946
39   1022876                          Country space in the city  49725315867
42   1024533                Beautiful Sunny Park Slope Brooklyn  50357575975
44   1025637                                  West Side Retreat  55430108992
108  1060984                Modern Brooklyn Apt., August sublet  38981444696
109  1061537                   1,800 sq foot in luxury building  18044628997
110  1062089  Sunny 2-story Brooklyn townhouse w deck and ga...  85201462079
111  1062641                Times Square, Safe, Clean and Cozy!  61210263217
112  1063194       Cozy Room #3, Landmark Home 1 Block to PRATT  85719117699
113  1063746                   Beautiful Apartment East Village  95420528585
130  1073135                           ACCOMMODATIONS GALORE #1  90525781448
131  1073687                            Sunny Room in New Condo  35058485479

    host_identity_verified host name neighbourhood group       neighbourhood  \
0              unconfirmed  Madaline            Brooklyn          Kensington
1                 verified     Jenna           Manhattan             Midtown
4                 verified    Lyndon           Manhattan         East Harlem
5                 verified  Michelle           Manhattan         Murray Hill
7              unconfirmed      Emma            Brooklyn  Bedford-Stuyvesant
8                 verified    Evelyn           Manhattan      Hell's Kitchen
9              unconfirmed      Carl           Manhattan     Upper West Side
11                verified      Alan           Manhattan     Upper West Side
38                verified     Joyce            Brooklyn            Bushwick
39                verified    Deanna            Brooklyn            Flatbush
42                verified     Alina            Brooklyn         South Slope
44             unconfirmed    Alford           Manhattan     Upper West Side
108            unconfirmed       Ned            Brooklyn        Williamsburg
109            unconfirmed      Emma           Manhattan              Harlem
110               verified      Alen            Brooklyn             Gowanus
111            unconfirmed     Kevin           Manhattan      Hell's Kitchen
112            unconfirmed    Miller            Brooklyn        Clinton Hill
113               verified  Penelope           Manhattan        East Village
130            unconfirmed    Daniel           Manhattan              Harlem
131               verified  Victoria            Brooklyn        Clinton Hill

           country country code instant_bookable  ...        room type  \
0    United States           US            False  ...     Private room
1    United States           US            False  ...  Entire home/apt
4    United States           US            False  ...  Entire home/apt
5    United States           US             True  ...  Entire home/apt
7    United States           US            False  ...     Private room
8    United States           US             True  ...     Private room
9    United States           US            False  ...     Private room
11   United States           US             True  ...  Entire home/apt
38   United States           US             True  ...  Entire home/apt
39   United States           US             True  ...     Private room
42   United States           US             True  ...  Entire home/apt
44   United States           US            False  ...     Private room
108  United States           US            False  ...  Entire home/apt
109  United States           US             True  ...     Private room
110  United States           US            False  ...  Entire home/apt
111  United States           US             True  ...     Private room
112  United States           US             True  ...     Private room
113  United States           US             True  ...  Entire home/apt
130  United States           US             True  ...  Entire home/apt
131  United States           US            False  ...     Private room

    Construction year    price service fee minimum nights  number of reviews  \
0              2020.0    $966        $193            10.0                9.0
1              2007.0    $142         $28            30.0               45.0
4              2009.0    $204         $41            10.0                9.0
5              2013.0    $577        $115             3.0               74.0
7              2009.0  $1,060        $212            45.0               49.0
8              2005.0  $1,018        $204             2.0              430.0
9              2015.0    $291         $58             2.0              118.0
11             2008.0    $606        $121             5.0               53.0
38             2005.0  $1,097        $219             2.0              231.0
39             2011.0  $1,020        $204             1.0                0.0
42             2020.0    $370         $74             3.0               15.0
44             2017.0    $856        $171             4.0               81.0
108            2017.0    $589        $118            30.0               29.0
109            2005.0    $839        $168             2.0              170.0
110            2011.0    $528        $106            30.0               19.0
111            2014.0     $66         $13             2.0              334.0
112            2014.0    $761        $152             2.0               19.0
113            2007.0    $523        $105             7.0               12.0
130            2005.0    $449         $90             3.0              155.0
131            2018.0    $930        $186             3.0              260.0

     review rate number  calculated host listings count  availability 365  \
0                   4.0                             6.0             286.0
1                   4.0                             2.0             228.0
4                   3.0                             1.0             289.0
5                   3.0                             1.0             374.0
7                   5.0                             1.0             219.0
8                   3.0                             1.0             180.0
9                   5.0                             1.0             375.0
11                  4.0                             1.0             163.0
38                  3.0                             2.0             214.0
39                  3.0                             1.0             356.0
42                  2.0                             1.0              33.0
44                  3.0                             1.0              86.0
108                 1.0                             1.0              83.0
109                 1.0                             1.0             258.0
110                 2.0                             1.0             400.0
111                 1.0                             2.0              34.0
112                 4.0                             6.0             203.0
113                 5.0                             1.0              35.0
130                 3.0                             3.0             410.0
131                 4.0                             1.0             388.0

                                           house_rules
0    Clean up and treat the home the way you'd like...
1    Pet friendly but please confirm with me if the...
4    Please no smoking in the house, porch or on th...
5                    No smoking, please, and no drugs.
7    House Guidelines for our BnB We are delighted ...
8    - Please clean up after yourself when using th...
9    NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....
11   My ideal guests would be warm, friendly, and r...
38   Please no shoes inside the house and no  smoki...
39   House Guidelines for our BnB We are delighted ...
42   No smoking inside. Since I have a dog, there a...
44   Free WiFi! * No smoking anywhere on property. ...
108  This is a pretty quiet house in a residential ...
109  No smoking, drugs, loud volume, loud partying ...
110  We ask that guest DO NOT host any additional g...
111  You will be very comfortable in our home but w...
112  No smoking in the apartment, even with the win...
113  Guests are expected to be respectful, kind, ne...
130  Tenant Agreement: House Rules: The landlord re...
131  Please leave your shoes in the entranceway.  I...

[20 rows x 21 columns]

In [13]:
data_set['host_identity_verified']= data_set['host_identity_verified'].str.upper()

In [15]:
data_set["price"]=data_set["price"].str.replace("$","")
data_set["price"]=data_set["price"].str.replace(",","")
data_set["price"]=data_set["price"].str.replace(" ","")
data_set["service fee"]=data_set["service fee"].str.replace("$","")
data_set["service fee"]=data_set["service fee"].str.replace(",","")
data_set["service fee"]=data_set["service fee"].str.replace(" ","")

In [16]:
data_set["price"]=data_set["price"].astype(int)
data_set["service fee"]=data_set["service fee"].astype(int)

In [ ]:
data_set.head()

,index,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,country,country code,...,room type,Construction year,price,service fee,minimum nights,number of reviews,review rate number,calculated host listings count,availability 365,house_rules
0,0,1001254,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,United States,US,...,Private room,2020.0,966,193,10.0,9.0,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1,1002102,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,United States,US,...,Entire home/apt,2007.0,142,28,30.0,45.0,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
2,2,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,United States,US,...,Entire home/apt,2009.0,204,41,10.0,9.0,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
3,3,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,United States,US,...,Entire home/apt,2013.0,577,115,3.0,74.0,3.0,1.0,374.0,"No smoking, please, and no drugs."
4,4,1005202,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,United States,US,...,Private room,2009.0,1060,212,45.0,49.0,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...

In [17]:
data_set.info()

<class 'pandas.DataFrame'>
Index: 48450 entries, 0 to 102040
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48450 non-null  int64
 1   NAME                            48450 non-null  str
 2   host id                         48450 non-null  int64
 3   host_identity_verified          48450 non-null  str
 4   host name                       48450 non-null  str
 5   neighbourhood group             48450 non-null  str
 6   neighbourhood                   48450 non-null  str
 7   country                         48450 non-null  str
 8   country code                    48450 non-null  str
 9   instant_bookable                48450 non-null  object
 10  cancellation_policy             48450 non-null  str
 11  room type                       48450 non-null  str
 12  Construction year               48450 non-null  float64
 13  price                           48450 non-null  int64
 14  service fee                     48450 non-null  int64
 15  minimum nights                  48450 non-null  float64
 16  number of reviews               48450 non-null  float64
 17  review rate number              48450 non-null  float64
 18  calculated host listings count  48450 non-null  float64
 19  availability 365                48450 non-null  float64
 20  house_rules                     48450 non-null  str
dtypes: float64(6), int64(4), object(1), str(10)
memory usage: 8.1+ MB

In [18]:
data_set.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'country', 'country code',
       'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'review rate number',
       'calculated host listings count', 'availability 365', 'house_rules'],
      dtype='str')

In [19]:
data_set.to_csv("clean_airbnb_file.csv")

In [20]:
data=pd.read_csv("clean_airbnb_file.csv")
data.head()

,Unnamed: 0,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,country,country code,...,room type,Construction year,price,service fee,minimum nights,number of reviews,review rate number,calculated host listings count,availability 365,house_rules
0,0,1001254,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,United States,US,...,Private room,2020.0,966,193,10.0,9.0,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1,1002102,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,United States,US,...,Entire home/apt,2007.0,142,28,30.0,45.0,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
2,4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,United States,US,...,Entire home/apt,2009.0,204,41,10.0,9.0,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
3,5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,United States,US,...,Entire home/apt,2013.0,577,115,3.0,74.0,3.0,1.0,374.0,"No smoking, please, and no drugs."
4,7,1005202,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,United States,US,...,Private room,2009.0,1060,212,45.0,49.0,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...