<a href="https://colab.research.google.com/github/MANDEEP9711/panda_practices-/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import pandas as pd
a=pd.Series([2,3,4,5])
print(a)

In [ ]:
import pandas as pd
a=pd.Series([2,3,4,5])
print(a)

0    2
1    3
2    4
3    5
dtype: int64

In [ ]:

dis={
    "name":["mandeep","kalu","balu","chalu"],
     "age":[24,25,27,38]
    }
var=pd.DataFrame(dis,columns=["name","age"],)
print(var)

      name  age
0  mandeep   24
1     kalu   25
2     balu   27
3    chalu   38

In [ ]:
var.to_csv("student_detail.csv")
csv_1=pd.read_csv("student_detail.csv",usecols=["name","age"],nrows=4,dtype={"age":"float"})
csv_1.insert(2,"gender",["male","male","male","male"])
print(csv_1)

      name   age gender
0  mandeep  24.0   male
1     kalu  25.0   male
2     balu  27.0   male
3    chalu  38.0   male

In [ ]:
import numpy as np
csv_1["sub"]=np.where(csv_1["age"]<=25,csv_1["age"],np.nan)
print(csv_1)

      name   age gender   sub
0  mandeep  24.0   male  24.0
1     kalu  25.0   male  25.0
2     balu  27.0   male   NaN
3    chalu  38.0   male   NaN

In [ ]:
import statistics as st
var1=[23,45,23,67,89,21,21]
print(st.mean(var1))
print(st.median(var1))
print(st.multimode(var1))

41.285714285714285
23
[23, 21]

In [ ]:
arr=var["age"]
print(st.mean(arr))
print(st.median(arr))

28.5
26.0

In [ ]:
arr=var["age"].to_numpy()
print(arr)

[24 25 27 38]

In [ ]:
import pandas as pd
merge_1=pd.DataFrame({"name":["a","f","c","d","e"],"age":[12,4,35,67,34]})
merge_2=pd.DataFrame({"name":["a","b","c","d"],"age":[21,42,5,7]})
pd.merge(merge_1,merge_2,on="name",how="outer",suffixes=("_left","_right"))

  name  age_left  age_right
0    a      12.0       21.0
1    b       NaN       42.0
2    c      35.0        5.0
3    d      67.0        7.0
4    e      34.0        NaN
5    f       4.0        NaN

In [ ]:
x=merge_1["age"].idxmin()
merge_1.loc[x]["name"]

'f'

# New Section

In [ ]:
pd.concat([merge_1,merge_2],axis=1,join="outer",ignore_index=True)

   0   1    2     3
0  a  12    a  21.0
1  f   4    b  42.0
2  c  35    c   5.0
3  d  67    d   7.0
4  e  34  NaN   NaN

In [ ]:
var1=pd.DataFrame({
    "name":["a","b","c","a","d","b","a","d","e"],
    "sub_1":[12,4,35,67,34,23,21,23,54],
    "sub_2":[23,21,56,78,34,56,32,45,67]
    })
value=var1.groupby("name")
for x,y in value:
    print(x)
    print()
    print(y)

a

  name  sub_1  sub_2
0    a     12     23
3    a     67     78
6    a     21     32
b

  name  sub_1  sub_2
1    b      4     21
5    b     23     56
c

  name  sub_1  sub_2
2    c     35     56
d

  name  sub_1  sub_2
4    d     34     34
7    d     23     45
e

  name  sub_1  sub_2
8    e     54     67

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("arianazmoudeh/airbnbopendata")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/arianazmoudeh/airbnbopendata/1.archive...

100%|██████████| 10.5M/10.5M [00:00<00:00, 128MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/arianazmoudeh/airbnbopendata/versions/1

In [ ]:
import numpy as np
import pandas as pd
import os

print(os.listdir(path))
fil=os.path.join(path,"Airbnb_Open_Data.csv")
print(fil)

['Airbnb_Open_Data.csv']
/root/.cache/kagglehub/datasets/arianazmoudeh/airbnbopendata/versions/1/Airbnb_Open_Data.csv

In [ ]:
data_set=pd.read_csv("/root/.cache/kagglehub/datasets/arianazmoudeh/airbnbopendata/versions/1/Airbnb_Open_Data.csv")
print(data_set.head(5))

        id                                              NAME      host id  \
0  1001254                Clean & quiet apt home by the park  80014485718
1  1002102                             Skylit Midtown Castle  52335172823
2  1002403               THE VILLAGE OF HARLEM....NEW YORK !  78829239556
3  1002755                                               NaN  85098326012
4  1003689  Entire Apt: Spacious Studio/Loft by central park  92037596077

  host_identity_verified host name neighbourhood group neighbourhood  \
0            unconfirmed  Madaline            Brooklyn    Kensington
1               verified     Jenna           Manhattan       Midtown
2                    NaN     Elise           Manhattan        Harlem
3            unconfirmed     Garry            Brooklyn  Clinton Hill
4               verified    Lyndon           Manhattan   East Harlem

        lat      long        country  ... service fee minimum nights  \
0  40.64749 -73.97237  United States  ...       $193            10.0
1  40.75362 -73.98377  United States  ...        $28            30.0
2  40.80902 -73.94190  United States  ...       $124             3.0
3  40.68514 -73.95976  United States  ...        $74            30.0
4  40.79851 -73.94399  United States  ...        $41            10.0

  number of reviews last review  reviews per month review rate number  \
0               9.0  10/19/2021               0.21                4.0
1              45.0   5/21/2022               0.38                4.0
2               0.0         NaN                NaN                5.0
3             270.0    7/5/2019               4.64                4.0
4               9.0  11/19/2018               0.10                3.0

  calculated host listings count  availability 365  \
0                            6.0             286.0
1                            2.0             228.0
2                            1.0             352.0
3                            1.0             322.0
4                            1.0             289.0

                                         house_rules license
0  Clean up and treat the home the way you'd like...     NaN
1  Pet friendly but please confirm with me if the...     NaN
2  I encourage you to use my kitchen, cooking and...     NaN
3                                                NaN     NaN
4  Please no smoking in the house, porch or on th...     NaN

[5 rows x 26 columns]

/tmp/ipykernel_8238/3091858918.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  data_set=pd.read_csv("/root/.cache/kagglehub/datasets/arianazmoudeh/airbnbopendata/versions/1/Airbnb_Open_Data.csv")

In [ ]:
data_set=data_set.drop(["last review","reviews per month","license","lat","long"],axis=1)
null_data=data_set.isnull().sum()

In [ ]:
null_data=data_set.isnull().sum()
data_set["house_rules"].fillna("no rules",inplace=True)
print(null_data)

id                                  0
NAME                              250
host id                             0
host_identity_verified            289
host name                         406
neighbourhood group                29
neighbourhood                      16
country                           532
country code                      131
instant_bookable                  105
cancellation_policy                76
room type                           0
Construction year                 214
price                             247
service fee                       273
minimum nights                    409
number of reviews                 183
review rate number                326
calculated host listings count    319
availability 365                  448
house_rules                         0
dtype: int64

In [ ]:
data_set.dropna(axis=0,inplace=True)
print(data_set)

             id                                              NAME  \
0       1001254                Clean & quiet apt home by the park
1       1002102                             Skylit Midtown Castle
4       1003689  Entire Apt: Spacious Studio/Loft by central park
5       1004098         Large Cozy 1 BR Apartment In Midtown East
7       1005202                                   BlissArtsSpace!
...         ...                                               ...
102594  6092437                        Spare room in Williamsburg
102595  6092990                     Best Location near Columbia U
102596  6093542                    Comfy, bright room in Brooklyn
102597  6094094                  Big Studio-One Stop from Midtown
102598  6094647                              585 sf Luxury Studio

            host id host_identity_verified    host name neighbourhood group  \
0       80014485718            unconfirmed     Madaline            Brooklyn
1       52335172823               verified        Jenna           Manhattan
4       92037596077               verified       Lyndon           Manhattan
5       45498551794               verified     Michelle           Manhattan
7       90821839709            unconfirmed         Emma            Brooklyn
...             ...                    ...          ...                 ...
102594  12312296767               verified         Krik            Brooklyn
102595  77864383453            unconfirmed        Mifan           Manhattan
102596  69050334417            unconfirmed        Megan            Brooklyn
102597  11160591270            unconfirmed  Christopher              Queens
102598  68170633372            unconfirmed      Rebecca           Manhattan

              neighbourhood        country country code instant_bookable  ...  \
0                Kensington  United States           US            False  ...
1                   Midtown  United States           US            False  ...
4               East Harlem  United States           US            False  ...
5               Murray Hill  United States           US             True  ...
7        Bedford-Stuyvesant  United States           US            False  ...
...                     ...            ...          ...              ...  ...
102594         Williamsburg  United States           US            False  ...
102595  Morningside Heights  United States           US             True  ...
102596           Park Slope  United States           US             True  ...
102597     Long Island City  United States           US             True  ...
102598      Upper West Side  United States           US            False  ...

              room type Construction year    price service fee minimum nights  \
0          Private room            2020.0    $966        $193            10.0
1       Entire home/apt            2007.0    $142         $28            30.0
4       Entire home/apt            2009.0    $204         $41            10.0
5       Entire home/apt            2013.0    $577        $115             3.0
7          Private room            2009.0  $1,060        $212            45.0
...                 ...               ...      ...         ...            ...
102594     Private room            2003.0    $844        $169             1.0
102595     Private room            2016.0    $837        $167             1.0
102596     Private room            2009.0    $988        $198             3.0
102597  Entire home/apt            2015.0    $546        $109             2.0
102598  Entire home/apt            2010.0  $1,032        $206             1.0

        number of reviews  review rate number  calculated host listings count  \
0                     9.0                 4.0                             6.0
1                    45.0                 4.0                             2.0
4                     9.0                 3.0                             1.0
5                    74.0                 3.0                             1.0
7                    49.0                 5.0                             1.0
...                   ...                 ...                             ...
102594                0.0                 3.0                             1.0
102595                1.0                 2.0                             2.0
102596                0.0                 5.0                             1.0
102597                5.0                 3.0                             1.0
102598                0.0                 3.0                             1.0

        availability 365                                        house_rules
0                  286.0  Clean up and treat the home the way you'd like...
1                  228.0  Pet friendly but please confirm with me if the...
4                  289.0  Please no smoking in the house, porch or on th...
5                  374.0                  No smoking, please, and no drugs.
7                  219.0  House Guidelines for our BnB We are delighted ...
...                  ...                                                ...
102594             227.0  No Smoking No Parties or Events of any kind Pl...
102595             395.0  House rules: Guests agree to the following ter...
102596             342.0                                           no rules
102597             386.0                                           no rules
102598              69.0                                           no rules

[99039 rows x 21 columns]

In [ ]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99039 entries, 0 to 102598
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              99039 non-null  int64
 1   NAME                            99039 non-null  object
 2   host id                         99039 non-null  int64
 3   host_identity_verified          99039 non-null  object
 4   host name                       99039 non-null  object
 5   neighbourhood group             99039 non-null  object
 6   neighbourhood                   99039 non-null  object
 7   country                         99039 non-null  object
 8   country code                    99039 non-null  object
 9   instant_bookable                99039 non-null  object
 10  cancellation_policy             99039 non-null  object
 11  room type                       99039 non-null  object
 12  Construction year               99039 non-null  float64
 13  price                           99039 non-null  object
 14  service fee                     99039 non-null  object
 15  minimum nights                  99039 non-null  float64
 16  number of reviews               99039 non-null  float64
 17  review rate number              99039 non-null  float64
 18  calculated host listings count  99039 non-null  float64
 19  availability 365                99039 non-null  float64
 20  house_rules                     99039 non-null  object
dtypes: float64(6), int64(2), object(13)
memory usage: 16.6+ MB

In [ ]:
data_set.drop_duplicates(inplace=True)
data_set.duplicated().sum()

np.int64(0)

In [ ]:
data_set.rename(columns={"level_0":"index"},inplace=True)
print(data_set.head(20))

    index       id                                               NAME  \
0       0  1001254                 Clean & quiet apt home by the park
1       1  1002102                              Skylit Midtown Castle
2       2  1003689   Entire Apt: Spacious Studio/Loft by central park
3       3  1004098          Large Cozy 1 BR Apartment In Midtown East
4       4  1005202                                    BlissArtsSpace!
5       5  1005754                    Large Furnished Room Near B'way
6       6  1006307                 Cozy Clean Guest Room - Family Apt
7       7  1006859                 Cute & Cozy Lower East Side 1 bdrm
8       8  1007411                   Beautiful 1br on Upper West Side
9       9  1008516     Lovely Room 1, Garden, Best Area, Legal rental
10     10  1009068   Wonderful Guest Bedroom in Manhattan for SINGLES
11     11  1022323                          Cute apt in artist's home
12     12  1022876                          Country space in the city
13     13  1023980                                ENJOY Downtown NYC!
14     14  1024533                Beautiful Sunny Park Slope Brooklyn
15     15  1025637                                  West Side Retreat
16     16  1060984                Modern Brooklyn Apt., August sublet
17     17  1061537                   1,800 sq foot in luxury building
18     18  1062089  Sunny 2-story Brooklyn townhouse w deck and ga...
19     19  1062641                Times Square, Safe, Clean and Cozy!

        host id host_identity_verified host name neighbourhood group  \
0   80014485718            unconfirmed  Madaline            Brooklyn
1   52335172823               verified     Jenna           Manhattan
2   92037596077               verified    Lyndon           Manhattan
3   45498551794               verified  Michelle           Manhattan
4   90821839709            unconfirmed      Emma            Brooklyn
5   79384379533               verified    Evelyn           Manhattan
6   75527839483            unconfirmed      Carl           Manhattan
7    1280143094               verified   Miranda           Manhattan
8   18824631834               verified      Alan           Manhattan
9   26802410424               verified     Darcy             brookln
10  88920244552               verified  Leonardo           Manhattan
11  88653822946               verified     Joyce            Brooklyn
12  49725315867               verified    Deanna            Brooklyn
13  63131487263            unconfirmed     Byron           Manhattan
14  50357575975               verified     Alina            Brooklyn
15  55430108992            unconfirmed    Alford           Manhattan
16  38981444696            unconfirmed       Ned            Brooklyn
17  18044628997            unconfirmed      Emma           Manhattan
18  85201462079               verified      Alen            Brooklyn
19  61210263217            unconfirmed     Kevin           Manhattan

         neighbourhood        country country code  ...        room type  \
0           Kensington  United States           US  ...     Private room
1              Midtown  United States           US  ...  Entire home/apt
2          East Harlem  United States           US  ...  Entire home/apt
3          Murray Hill  United States           US  ...  Entire home/apt
4   Bedford-Stuyvesant  United States           US  ...     Private room
5       Hell's Kitchen  United States           US  ...     Private room
6      Upper West Side  United States           US  ...     Private room
7            Chinatown  United States           US  ...  Entire home/apt
8      Upper West Side  United States           US  ...  Entire home/apt
9          South Slope  United States           US  ...     Private room
10     Upper West Side  United States           US  ...     Private room
11            Bushwick  United States           US  ...  Entire home/apt
12            Flatbush  United States           US  ...     Private room
13        East Village  United States           US  ...     Private room
14         South Slope  United States           US  ...  Entire home/apt
15     Upper West Side  United States           US  ...     Private room
16        Williamsburg  United States           US  ...  Entire home/apt
17              Harlem  United States           US  ...     Private room
18             Gowanus  United States           US  ...  Entire home/apt
19      Hell's Kitchen  United States           US  ...     Private room

   Construction year    price  service fee minimum nights number of reviews  \
0             2020.0    $966         $193            10.0               9.0
1             2007.0    $142          $28            30.0              45.0
2             2009.0    $204          $41            10.0               9.0
3             2013.0    $577         $115             3.0              74.0
4             2009.0  $1,060         $212            45.0              49.0
5             2005.0  $1,018         $204             2.0             430.0
6             2015.0    $291          $58             2.0             118.0
7             2004.0    $319          $64             1.0             160.0
8             2008.0    $606         $121             5.0              53.0
9             2010.0    $580         $116             4.0             167.0
10            2019.0    $149          $30             2.0             113.0
11            2005.0  $1,097         $219             2.0             231.0
12            2011.0  $1,020         $204             1.0               0.0
13            2005.0    $563         $113             2.0             245.0
14            2020.0    $370          $74             3.0              15.0
15            2017.0    $856         $171             4.0              81.0
16            2017.0    $589         $118            30.0              29.0
17            2005.0    $839         $168             2.0             170.0
18            2011.0    $528         $106            30.0              19.0
19            2014.0     $66          $13             2.0             334.0

    review rate number  calculated host listings count  availability 365  \
0                  4.0                             6.0             286.0
1                  4.0                             2.0             228.0
2                  3.0                             1.0             289.0
3                  3.0                             1.0             374.0
4                  5.0                             1.0             219.0
5                  3.0                             1.0             180.0
6                  5.0                             1.0             375.0
7                  3.0                             4.0               1.0
8                  4.0                             1.0             163.0
9                  4.0                             3.0              47.0
10                 3.0                             1.0              68.0
11                 3.0                             2.0             214.0
12                 3.0                             1.0             356.0
13                 3.0                             2.0             354.0
14                 2.0                             1.0              33.0
15                 3.0                             1.0              86.0
16                 1.0                             1.0              83.0
17                 1.0                             1.0             258.0
18                 2.0                             1.0             400.0
19                 1.0                             2.0              34.0

                                          house_rules
0   Clean up and treat the home the way you'd like...
1   Pet friendly but please confirm with me if the...
2   Please no smoking in the house, porch or on th...
3                   No smoking, please, and no drugs.
4   House Guidelines for our BnB We are delighted ...
5   - Please clean up after yourself when using th...
6   NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....
7                                            no rules
8   My ideal guests would be warm, friendly, and r...
9                                            no rules
10                                           no rules
11  Please no shoes inside the house and no  smoki...
12  House Guidelines for our BnB We are delighted ...
13                                           no rules
14  No smoking inside. Since I have a dog, there a...
15  Free WiFi! * No smoking anywhere on property. ...
16  This is a pretty quiet house in a residential ...
17  No smoking, drugs, loud volume, loud partying ...
18  We ask that guest DO NOT host any additional g...
19  You will be very comfortable in our home but w...

[20 rows x 22 columns]

In [ ]:
data_set['host_identity_verified']= data_set['host_identity_verified'].str.upper()

In [ ]:
data_set["price"]=data_set["price"].str.replace("$","")
data_set["price"]=data_set["price"].str.replace(",","")
data_set["price"]=data_set["price"].str.replace(" ","")
data_set["service fee"]=data_set["service fee"].str.replace("$","")
data_set["service fee"]=data_set["service fee"].str.replace(",","")
data_set["service fee"]=data_set["service fee"].str.replace(" ","")

In [ ]:
data_set["price"]=data_set["price"].astype(int)
data_set["service fee"]=data_set["service fee"].astype(int)

In [ ]:
data_set.head()

,index,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,country,country code,...,room type,Construction year,price,service fee,minimum nights,number of reviews,review rate number,calculated host listings count,availability 365,house_rules
0,0,1001254,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,United States,US,...,Private room,2020.0,966,193,10.0,9.0,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1,1002102,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,United States,US,...,Entire home/apt,2007.0,142,28,30.0,45.0,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
2,2,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,United States,US,...,Entire home/apt,2009.0,204,41,10.0,9.0,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
3,3,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,United States,US,...,Entire home/apt,2013.0,577,115,3.0,74.0,3.0,1.0,374.0,"No smoking, please, and no drugs."
4,4,1005202,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,United States,US,...,Private room,2009.0,1060,212,45.0,49.0,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...

In [ ]:
data_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98516 entries, 0 to 98515
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   index                           98516 non-null  int64
 1   id                              98516 non-null  int64
 2   NAME                            98516 non-null  object
 3   host id                         98516 non-null  int64
 4   host_identity_verified          98516 non-null  object
 5   host name                       98516 non-null  object
 6   neighbourhood group             98516 non-null  object
 7   neighbourhood                   98516 non-null  object
 8   country                         98516 non-null  object
 9   country code                    98516 non-null  object
 10  instant_bookable                98516 non-null  object
 11  cancellation_policy             98516 non-null  object
 12  room type                       98516 non-null  object
 13  Construction year               98516 non-null  float64
 14  price                           98516 non-null  int64
 15  service fee                     98516 non-null  int64
 16  minimum nights                  98516 non-null  float64
 17  number of reviews               98516 non-null  float64
 18  review rate number              98516 non-null  float64
 19  calculated host listings count  98516 non-null  float64
 20  availability 365                98516 non-null  float64
 21  house_rules                     98516 non-null  object
dtypes: float64(6), int64(5), object(11)
memory usage: 16.5+ MB

In [ ]:
data_set.columns

Index(['index', 'id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'country', 'country code',
       'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'review rate number',
       'calculated host listings count', 'availability 365', 'house_rules'],
      dtype='object')

In [ ]:
data_set.to_csv("clean_airbnb_file.csv")

In [ ]:
data=pd.read_csv("clean_airbnb_file.csv")
data.head()

,Unnamed: 0,index,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,country,...,room type,Construction year,price,service fee,minimum nights,number of reviews,review rate number,calculated host listings count,availability 365,house_rules
0,0,0,1001254,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,United States,...,Private room,2020.0,966,193,10.0,9.0,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1,1,1002102,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,United States,...,Entire home/apt,2007.0,142,28,30.0,45.0,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
2,2,2,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,United States,...,Entire home/apt,2009.0,204,41,10.0,9.0,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
3,3,3,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,VERIFIED,Michelle,Manhattan,Murray Hill,United States,...,Entire home/apt,2013.0,577,115,3.0,74.0,3.0,1.0,374.0,"No smoking, please, and no drugs."
4,4,4,1005202,BlissArtsSpace!,90821839709,UNCONFIRMED,Emma,Brooklyn,Bedford-Stuyvesant,United States,...,Private room,2009.0,1060,212,45.0,49.0,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...

In [97]:
from google.colab import files

files.download("clean_airbnb_file.csv")